### ISSUE TITLE
"Could not find project root"

### ISSUE THREAD

**Issue by ethzero** [csch0/SublimeText-File-Navigator#2]
I'm quite new to Sublime Text 2 and this plugin so apologies if I've missed a simple or critical step.

Put simply, when I try to invoke the navigator I get: "Could not find project root"

I'm at a loss to how or where this is defined; is it part of this plugin's settings or Sublime etc?

**Comment by belike81** [comment]
Hi,

Sorry for the late response, but I was unavailable earlier. Since you
already closed the issue I assume that you found the answer to your
question.

Basically you need to have a root directory set to use the plugin, and to
do that You either have to add a folder to you project or open Sublime from
your command line with a folder path as a parameter.

Hope that clears things up.

Best regards,
Tomasz Grabowski
www: www.tomaszgrabowski.com

On Sat, Apr 14, 2012 at 10:11 AM, eth0 <
reply@reply.github.com

**Comment by ethzero** [comment]
Hi Tomasz, I did indeed find the answer... I need to make a _project_ and not use your plugin as an arbitrary/alternative "File Open" dialog! - Cheers
