### ISSUE TITLE
Plugin is too slow

### ISSUE THREAD

**Issue by samholmes** [csch0/SublimeText-File-Navigator#5]
I'm interesting in see some improvements being made in the speed of this plugin. Currently, it takes too long for the menu to appear after pressing Ctrl+Shift+O, this wait time interferes with my workflow and has made me use this plugin a lot less. Snappy response is what this plugin needs in order to be successful. 

What's causing this problem?

**Comment by belike81** [comment]
The plugin has some bugs that I don't really have time to resolve at the moment, as I'm not using Sublime for work (came back to VIM). Most likely you are opening a really big folder (it works fine on most of my projects), like the root of your projects directory. Because of the flawed way it currently works it gets slow if you do that.

If you feel like it please fork the project and fix this bug, then issue I pull request and I'll be happy to merge it to master.

**Comment by samholmes** [comment]
I don't know python. But maybe I could learn it. However, where can I learn the sublime text API; where do you go for that resource?
